### ISSUE TITLE
Publish latest successful master-branch builds

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#31] opened 2019-11-03 03:27 UTC
Packaging the latest builds from `master` will allow users to test and provide feedback regarding newly-integrated features.  Feedback, both good and bad, is critical toward building confidence in the technical work, the people involved, and the process here regarding git and its workflow.

Import aspects:
- **Obvious and easy versioning** - a commit identifier should be readily available for feedback and issue reporting. It should be easier to find the version that it is to _not_ find it; if that makes sense.
- **low barrier of entry** - beginners should be able to run the binary without requiring esoteric DLLs or installing some percent of the development tools. This "threshold" might be different based on the OS; for example, on Linux perhaps we can ask users to `apt install -y sdl sdl_net opusfile`, where as Windows and OS X users we can package those libraries inside the zip/dmg file.
- **expiration** - ideally only the current latest build should be available. Old packages should be removed once new ones are available. With limited man-power, this will keep the focus on the current state of master.

**Comment by dreamer** [comment] 2019-11-12 11:27
I am looking at this and there is no perfect way of uploading builds on GitHub right now :/

I consider GitLab CI way the perfect solution: a deploy step can be added in the CI job and files get uploaded to GitLab pages (simple and effective).

It seems like GitHub solution requires generating a commit in gh-pages branch in current repo (or in a dedicated repo for GitHub org)…

- does it handle binary artifacts correctly via git-lfs? (not clear)
- does it upload files immediately or do we need to wait hours before all files are distributed throughout the world? (not clear)
- are there any limits for hosted files? (not clear - there is only my monthly limit of LFS artifact downloads).

So we have at least these options:

1. Uploading artifacts to gh-pages branch (hopefully git-lfs works); I really, really don't like the idea of storing nightly build artifacts on a branch in this repo… Right now repo is healthy 34MB, which is fast to clone, checkout and deploys in CI immediately - adding automatically-generated stuff on a branch, will make it bloated in time.
2. Uploading artifacts to repo dedidacted for publishing GitHub Pages - better solution, but we would need a GitHub org (which we should probably create anyway). Somebody is squatting `dosbox` org name - I'll send a GitHub request for re-assign.
3. Duplicating build process in other CI(s) and uploading build results in there. AFAIK only GitLab offers this in free tier, and only for Linux builds… so this option is probably a no-go.

Unless I'll finding something better, I'll start moving towards (2).

**Comment by krcroft** [comment] 2019-11-12 13:34
Assuming we can upload a tar/zip, (webDAV; a one-liner in curl or wget), and then link to the assets on our github pages or wiki: would that be an option?

Although not a entirely bomb proof, I have my home 24/7 server, 20Mbit-upload speeds, and could carve out say 500MB or more on a pure-ram area where newer uploads would evict the older ones.

**Comment by dreamer** [comment] 2019-11-12 23:38
Such a stupid problem, especially considering, that GitHub offers free hosting for binary files if they are manually attached to a comment or release page :/

I feel, that using private server might be too inconvenient (and people might have problems with downloading from it if it'll be non-https), but it's an option.

One thing that just crossed my mind is uploading artefacts (we are only talking about nightly builds here) to IPFS or as torrents - we could configure our home servers to download artefacts automatically after nightly build and commit only magnet links or .torrent files to GitHub Pages.

**Comment by krcroft** [comment] 2019-11-12 23:50
Yes - totally regarding home servers.. just too hard to guarantee the uptime (reboots, powering down when going on vacation, and so on); absolutely not ideal.  

Love the artefacts and pooled torrent strategy!  I could see some vogoner's adding their systems to the pool. 

I'm not sure if GitHub's URLs to the nightlies would be constant (or predictable?) or if we'd have to wrestle it out dynamically with some beautiful soup or something.  Likewise regarding posting to GitHub pages.. those are all new to me.  But excited about the options!

**Comment by dreamer** [comment] 2019-11-13 00:10
Artefacts attached to named releases have predictable names, e.g. one of test builds I manually uploaded to previous Boxtron releases is available at: https://github.com/dreamer/boxtron/releases/download/v0.5.3/dosbox-staging-2.tar.xz

I think https://developer.github.com/v3/repos/releases/#upload-a-release-asset might be the way to go. It could work this way: create a pre-release - following semantic versioning and git convention it could be something like: `v0.75.0-alpha.1` or maybe simply tag named `nightly`, attached to nothing in particular (e.g. empty disconnected branch), then keep removing old/uploading new nightly builds as "assets" to that release. So the URL would could look like this:

- https://github.com/dreamer/dosbox-staging/releases/download/nightly/dosbox-staging-nightly-linux-latest.tar.xz
- https://github.com/dreamer/dosbox-staging/releases/download/nightly/dosbox-staging-nightly-linux-191113.tar.xz
- https://github.com/dreamer/dosbox-staging/releases/download/nightly/dosbox-staging-nightly-windows-latest.zip
- https://github.com/dreamer/dosbox-staging/releases/download/nightly/dosbox-staging-nightly-windows-191113.zip
- (and whatever format is native for macOS)

Stable links pointing to "*-latest*" could go to README.md file - this way we wouldn't need to maintain GitHub Page.

Perhaps it's time to create a prototype and test the limits of GitHub API…

**Comment by krcroft** [comment] 2019-11-13 01:40
Nice digging.
> Perhaps it's time to create a prototype and test the limits of GitHub API…
Definitely agree!

**Comment by LowLevelMahn** [comment] 2019-11-16 07:42
take a look how the watcom v2 projects is doing it: daily build releases for various platforms

https://github.com/open-watcom/open-watcom-v2/releases
https://github.com/open-watcom/open-watcom-v2/issues/554

**Comment by dreamer** [comment] 2019-11-16 12:59
It seems like OpenWatcom uses the strategy I described in my previous post: a release page with dynamically uploaded assets (I can't find specific place in the CI that uploads the assets, but I guess they don't do it manually). CI configuration in that project is a bit hard to read, as they use 2 CIs (GitHub Actions and Azure Pipelines).

**Comment by dreamer** [comment] 2019-11-26 02:18
Few notes to myself, as I was investigating replacing `Bitu` and friends and hit a few issues in the process… and this is relevant to release builds:

- ATM, our debug builds happen without `--enable-debug` flag (this flag turns on internal DOSBox debugger using *curses). Some (not all) of debug builds should have this turned ON - turning it on brings several hundred of new warnings (mostly `format` warnings). We need to make sure, that debug builds have some kind of ncurses package installed. INSTALL file says, that it needs to be `pdcurses` (which is packaged by very few repos), but the autoconf will work fine with `ncurses` or other packages as well.
- For release builds, we need to make sure, that this package is NOT installed (we need to handle build with and without this package) and without `--enable-debug`.
- I don't know what to do with this flag and code analysis builds - I think turning it on will probably break sanitizer builds, but it should work with static analysis builds - not sure.
- We should probably also define DEBUG/NDEBUG flags for various builds as well… NDEBUG enabled and DEBUG disabled should be the conf for Release builds, I think.

**Comment by krcroft** [comment] 2020-01-27 04:53
@dreamer ; given your progress in generating release builds for Linux and Windows, and naming them uniquely inside the zips, I believe this issue's intent has been accomplished.

Some might disagree this should be held open until macOS (and ARM, and, AmigaOS, and Linux PPC, and ... ) binaries are available too; but the mechanism and model for this is now in place and working. So if/when demand for those other builds arise, we can open a specific issue and tackle them then.
Propose we close this.

**Comment by dreamer** [comment] 2020-01-27 10:19
@krcroft Agreed.

I tried to set up macOS in VirtualBox to create/test macOS packages, but I can't run it - besides very user-unfriendly process of preparing macOS VM, the installation process just doesn't start - I suspect it's caused by my processor not supporting certain virtualization extensions (Haswell, K-series) - although it's not a problem for *basically any other OS in the world*.

Preparing macOS snapshots should be discussed in #148 
Preparing ARM-based snapshots should be discussed in #2 

Snapshots for other OSes or architectures should be discussed in their own new issues; closing this one down.

**Closed by dreamer** 2020-01-27 10:19 UTC
Labels: enhancement
