### ISSUE TITLE
Mouse cursor visibility issues

### ISSUE THREAD

**Issue by nemo93** [dreamer/dosbox-staging#242] opened 2020-03-27 12:13 UTC
Another ticket to report an annoying bug with respect to the mouse cursor. 

* Description
System cursor is always apparent (by default top-left corner) whatever value is set for `capture_mouse =`. On some games (ie. Command & Conquer or Red Alert) the system cursor will blend/superpose with the game cursor hence it's not that a big problem. Yet on game like Theme Hospital for instance cursors won't blend and game cursor will act as a "ghost". It's like having 2 cursors on the screen which is annoying.

* To Reproduce
Launch Theme Hospital (HOSPITAL.EXE) or whatever game which requires a mouse. In Theme Hospital at the main menu (where a doctor points the various options) the cursor won't blend with the game. Meaning 2 cursors are apparent on the screen. I haven't compiled Dosbox with screenshot support :(
NOTE: with the current Dosbox SVN (default in Retropie) no problem with cursor. No system cursor apparent only the one from the game.
NOTE2: if a value different from `capture_mouse    = seamless middlerelease` is being set then mouse in the game won't work. System cursor will still be there and working but you can't control the game.

* Expected behaviour
No system cursor visible. Just the one from the current game.

* Environment:
Raspbian Jessie (the one shipped with Retropie+all packages up-to-date)
Retropie Version 4.5.18 (latest)
Pi3B+
SDL2 (no dispmanx)
I've compiled Dosbox-staging this morning after I saw the commits for SDL texture.

* Dosbox config (Theme Hospital)
```
fullscreen       = true
vsync            = false
fullresolution   = desktop
windowresolution = desktop
output           = texture
texture_renderer = auto
capture_mouse    = seamless middlerelease
sensitivity      = 100
waitonerror      = true
priority         = higher,normal
mapperfile       = mapper-SVN.map

language = 
machine  = svga_s3
captures = capture
memsize  = 16

frameskip = 0
aspect    = true
scaler = none

core = dynamic
cputype   = auto
cycles = max
cycleup   = 10
cycledown = 20
[...] // everything else as default
```

**Comment by dreamer** [comment] 2020-03-27 15:13
Usual behaviour in dosbox-staging is that cursor disappears always when entering the game window and we did remove few lines that, according to SDL2 documentation, were unnecessary - perhaps that was an error.

We'll need some more info to investigate and fix this properly:

- Exact version of SDL2, that you have installed (do you use the one from repo or maybe compiled one yourself?)
- Your desktop environment / generally environment you are testing in (with DE/without DE, via Koji or some frontend, etc)
- Do you use mouse or some other input device emulating mouse (e.g. Steam controller?)
- Wayland or X11?

**Comment by krcroft** [comment] 2020-03-27 15:58
Reproduced on Rpi3 running debian buster. 

SDL2 on the raspberry pi renders to the raw console frame buffer (without X11 or Wayland).

> cursor disappears always when entering the game window and we did remove few lines that, according to SDL2 documentation, were unnecessary

Yeah; hopefully we can figure out a general approach to hiding the host cursor and avoid special handling for the Pi.

**Comment by nemo93** [comment] 2020-03-27 17:16
Retropie might use its own SDL2 version ([here](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/sdl2.sh)). That's what I got today anyway:
```
$ sdl2-config --version
2.0.10
```
I do confirm everything said @krcroft. There's no DE of any kind with Retropie/Pi. Everything rendered straight to the console via FB. I'm using a Xbox one S controller in addition to my keyboard/mouse.

Thanks again.

**Comment by krcroft** [comment] 2020-03-27 21:21
Hmm; the SDL_WINDOWEVENT_EXPOSED event is never fired on the Pi during the startup event sequence, which itself is a bit dizzying. 

Here's a sequence log of the `SDL_WINDOWEVENT_*`'s fired on startup:

| Sequence | Linux on FB-Pi3  | Linux on X11-X86_64  |
|:--:|:--|:--|
| 1 | ENTER  | SIZE_CHANGED  |
| 2 | FOCUS_GAINED  | HIDDEN  |
| 3 |  SHOWN | SIZE_CHANGED |
| 4 | SIZE_CHANGED  | SHOWN  |
| 5 | HIDDEN  | ENTER |
| 6 | FOCUS_GAINED  | FOCUS_GAINED  |
| 7 | SHOWN  |  TAKE_FOCUS |
| 8 |  SIZE_CHANGED | MOVED  |
| 9 | HIDDEN  |  EXPOSED |
| 10 | FOCUS_GAINED  |   |
| 11 |  SHOWN |   |

**Comment by krcroft** [comment] 2020-03-27 22:23
@nemo93 , can you give branch `kc/rpi-cursor-1` a try? 

This behaves well on x86_64 Linux and the Pi3, across the following eight combinations:

```
# fullscreen    = true
# capture_mouse = nomouse 

# fullscreen    = true
# capture_mouse = onstart 

# fullscreen    = true
# capture_mouse = onclick 

# fullscreen    = true
# capture_mouse = seamless 

# fullscreen    = false
# capture_mouse = nomouse 

# fullscreen    = false
# capture_mouse = onstart 

# fullscreen    = false
# capture_mouse = onclick 

# fullscreen    = false
# capture_mouse = seamless 
```

When I tested each one, I toggled full & windowed modes, maximum / minimize, and mouse release & lock actions (although on the Pi we can't minimize; likewise releasing doesn't make much sense, so for actual gaming there I use "middlegame" instead of "middlerelease").

**Comment by nemo93** [comment] 2020-03-28 11:38
I confirm this branch does fix the issue. No more host cursor visible (to be picky cursor still apppears during the dosbox-staging logo display). I've tested with a bunch of games without any issue.

**Comment by krcroft** [comment] 2020-03-28 14:05
> to be picky cursor still apppears during the dosbox-staging logo display

Yup (and I'm picky too :-). For the years prior to dosbox-staging, I've been using SVN with an "onstart" patch to similarly hide the cursor on startup because I was equally annoyed with the cursor sitting in the upper left (I grew tired of needing to mouse click to capture and hide it.. ).

Right now in staging, the cursor's capture state is fully represented by a single tracking variable - which was a deliberate simplification from upstream.

I'm worried I would have to introduce a second state-tracking variable to track sursor visibility early in startup.  Not because variables are expensive; but because juggling multiple states adds complexity (2 booleans allows for 4 combinations). That said, I'll see if I can do it without a tracking variable (that way it won't upset the working balance of logic we have right now).

**Comment by nemo93** [comment] 2020-03-28 14:41
Don't waste time on that please. It's super fine as it is. Thanks again!

**Comment by dreamer** [comment] 2020-03-28 17:36
Wait a moment, we don't have this test branch merged in master yet! @krcroft is still working on it - I think we want this issue kept open until the problem is fixed in master?

@nemo93 @krcroft What do you think? To be reopened for now?

**Comment by krcroft** [comment] 2020-03-28 18:07
Yes; reopening for now just as a formality.  We'll let the merged PR automatically close it. Will move the PR out of draft when it's ready.

**Closed** 2020-03-30 19:48 UTC
Labels: Raspberry Pi, SDL2, bug
